version: "3.9"

services:
    web-server:
        container_name: web-server
        image: nginx:1.21.1
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./public/:/var/www/public/
        ports:
            - "2000:80"
        depends_on:
            - app

    app:
        container_name: app
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/
            - ./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    db:
        container_name: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./tmp/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "4000:3306"
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - "8080:8080"
#  cached:
#  queue:
